# Generated by Django 5.2 on 2025-10-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='Heure_Fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cours',
            name='Heure_commencer',
            field=models.TimeField(),
        ),
    ]
