# Generated by Django 5.2 on 2025-10-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_alter_cours_heure_fin_alter_cours_heure_commencer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='Heure_Fin',
            new_name='heure_fin',
        ),
        migrations.AddField(
            model_name='cours',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], default='Lundi', max_length=10),
        ),
    ]
