# Generated by Django 5.2 on 2025-10-31 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_rename_heure_fin_cours_heure_fin_cours_jour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='Heure_commencer',
            new_name='heure_commencer',
        ),
    ]
