# Generated by Django 5.2 on 2025-10-31 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('absent', 'Absent'), ('present', 'Présent')], default='absent', max_length=10)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='etudiants.etudiant')),
            ],
        ),
    ]
